baseurl: "https://omniopencon.org"
title: "OmniOpenCon"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "G-6YLFK34GVP"

params:
  # Conference info
  Name: "OmniOpenCon"
  Description: "A gathering of people, projects and communities working with open source / data / science / hardware / education"
  Date: "October 17-19, 2025"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Central Library, POLITEHNICA Bucharest"
  Address: "POLITEHNICA Bucharest - Splaiul Independenței 313"
  City: "Bucharest"
  #State: "Quintana"
  MapsLocation: "UNSTPB Central Library"
  Images: ["/img/badge.png"]
  GoogleMapsKey: "AIzaSyDqFddms1X_dFHRSDfvDVzUHGJG8D49yno"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    #- connect
    #- speakers
    #- orgs
    - cfs
    - schedule
    #- sponsors
    - organizers
    - conduct
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    #connect: "Get Connected!"
    #speakers: "Speakers"
    #orgs: "Orgs"
    cfs: "Call for Speakers"
    schedule: "Schedule"
    #sponsors: "Sponsors"
    partners: "Partners"
    organizers: "Organizers"
    conduct: "Code of Conduct"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://lu.ma/6ppjy6e5"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/rosedu/omniopencon"

  Contact:
    - name: "E-mail"
      logo: "/img/logo-email.png"
      url: "mailto:contact@omniopencon.org"
    - name: "Discord"
      logo: "/img/logo-discord.jpg"
      url: "https://bit.ly/OmniOpenConDiscord"

  # List of Sponsors
  Sponsors:
    - name: "Keysight Technologies Romania"
      logo: "/img/logo-keysight.png"
      url: "https://www.linkedin.com/company/ixia-romania/"

  # List of Partners
  #Partners:
  #  - name: "Liga Studenților din Facultatea de Automatică și Calculatoare (LSAC)"
  #    logo: "/img/logo-lsac.png"
  #    url: "https://lsacbucuresti.ro/"

  # List of Organizers
  Organizers:
    - name: "POLITEHNICA Bucharest"
      logo: "/img/logo-unstpb.png"
      url: "https://www.upb.ro"
    - name: "Faculty of Automatic Controls and Computers"
      logo: "/img/logo-acs.png"
      url: "https://acs.pub.ro"
    - name: "ROSEdu (Romanian Open Source Education)"
      logo: "/img/logo-rosedu.png"
      url: "https://www.rosedu.org"

  # The entire schedule
  Talks:
    - name: "Check-in"
      time: "08:30"
      description: "Welcome, get to know the venue, connect with others."

    - name: "Opening"
      time: "09:00"
      entries:
        - name: "Opening"
          interval: "09:00"
          location: "Aula Magna"
        - name: "Keynote: How to Make Money in Open Source"
          interval: "09:15"
          person: "Vicențiu Ciorbaru"
          location: "Aula Magna"
          photo: "/img/speakers/vicentiu.ciorbaru.jpg"
          ref: 11
        - name: "Keynote: How I found my voice in open source"
          interval: "09:45"
          person: "Georgiana Dolocan"
          location: "Aula Magna"
          photo: "/img/speakers/georgiana.dolocan.jpg"
          ref: 15


    - name: "Coffee / Tea Break"
      time: "10:30"
      location: "Aula Magna Hallway"
      description: "A well deserved break. Grab some coffee or tea, connect with others."

    - name: "Talks (session 2)"
      time: "11:00"
      locations:
        - Aula Magna
        - B3.1
        - B3.2
        - B4.1
      timeSlots:
        - interval: "11:00"
          entries:
            - ref: 12
            - ref: 33
            - ref: 48
            - ref: 41
        - interval: "11:30"
          entries:
            - ref: 1
              coSpeakerRef: 8
            - ref: 20
            - ref: 3
            - ref: 4
        - interval: "12:00"
          entries:
            - ref: 18
            - ref: 45
            - ref: 36
            - ref: 26

    - name: "Lunch Break"
      time: "12:30"
      location: "Aula Magna Hallway & around UPB Campus"
      description: "Lunch break. We will order (a LOT of) pizza. Dining options around the POLITEHNICA campus will also be provided."

    - name: "Talks (session 3)"
      time: "14:00"
      locations:
        - Aula Magna
        - B3.1
        - B3.2
        - B4.1
      timeSlots:
        - interval: "14:00"
          entries:
            - ref: 28
            - ref: 47
            - ref: 39
            - ref: 29
        - interval: "14:30"
          entries:
            - ref: 49
            - ref: 6
            - ref: 44
            - ref: 43
        - interval: "15:00"
          entries:
            - ref: 34
            - ref: 16
            - ref: 23
            - ref: 22

    - name: "Coffee / Tea Break"
      time: "15:30"
      location: "Aula Magna Hallway"
      description: "A well deserved break. Grab some coffee or tea, connect with others."

    - name: "Talks (session 4)"
      time: "16:00"
      locations:
        - Aula Magna
        - B3.1
        - B3.2
        - B4.1
      timeSlots:
        - interval: "16:00"
          entries:
            - ref: 35
            - ref: 7
            - ref: 38
            - ref: 52
        - interval: "16:30"
          entries:
            - ref: 50
            - ref: 31
            - ref: 14
            - ref: 53
        - interval: "17:00"
          entries:
            - ref: 19
            - ref: 54

    - name: "Networking"
      time: "17:30"
      description: "On-site networking with speakers, organizers, participants. A good time to make friends and open up collaboration options."

  Workshops:
    - name: "Check-in"
      time: "08:30"
      description: "Welcome, get to know the venue, connect with others."

    - name: "Workshops (session 1)"
      time: "09:00"
      description: "First workshop slot"
      locations:
        - B3.1
        - B3.2
        - B4.1
        - B4.2
      timeSlots:
        - interval: "09:00"
          entries:
            - ref: 37
            - ref: 46
            - ref: 17
            - ref: 2
        - interval: "11:00"
          entries:
            - ref: 27
            - ref: 40
            - ref: 5
            - ref: 10
              coEntryRef: 30

    - name: "Lunch Break"
      time: "12:30"
      location: "Library 4th Floor and around UPB Campus"
      description: "Lunch break. We will order (a LOT of) pizza. Dining options around the POLITEHNICA campus will also be provided."

    - name: "Workshops (session 2)"
      time: "14:00"
      description: "Second workshop slot"
      locations:
        - B3.1
        - B3.2
        - B4.1
        - B4.2
      timeSlots:
        - interval: "14:00"
          entries:
            - ref: 25
            - ref: 13
            - ref: 42
            - ref: 32
        - interval: "16:00"
          entries:
            - ref: 9
            - ref: 21

    - name: "Networking"
      time: "17:30"
      description: "On-site networking with speakers, organizers, participants. A good time to make friends and open up collaboration options."
