baseurl: "https://omniopencon.org/2026"
title: "OmniOpenCon"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: "G-6YLFK34GVP"

params:
  # Conference info
  Name: "OmniOpenCon"
  Description: "A gathering of people, projects and communities working with open source / data / science / hardware / education"
  Date: "October 16-17, 2026"
  #Price: "Only $100" # If your event is free, just comment this line
  Venue: "Central Library, POLITEHNICA Bucharest"
  Address: "POLITEHNICA Bucharest - Splaiul Independenței 313"
  City: "Bucharest"
  #State: "Quintana"
  MapsLocation: "UNSTPB Central Library"
  Images: ["/img/badge.png"]
  GoogleMapsKey: "AIzaSyDqFddms1X_dFHRSDfvDVzUHGJG8D49yno"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - cfs
    #- schedule
    - sponsors
    - partners
    - organizers
    - conduct
    - contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    cfs: "Call for Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    organizers: "Organizers"
    conduct: "Code of Conduct"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://luma.com/hi08i10q"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  ForkButton:
    repository: "https://github.com/rosedu/omniopencon"

  Contact:
    - name: "E-mail"
      logo: "/img/logo-email.png"
      url: "mailto:contact@omniopencon.org"
    - name: "Discord"
      logo: "/img/logo-discord.jpg"
      url: "https://bit.ly/OmniOpenConDiscord"

  # Past editions links shown in the "Past Editions" nav dropdown
  PastEditions:
    - name: "2024 Edition"
      url: "https://omniopencon.org/2024"
    - name: "2025 Edition"
      url: "https://omniopencon.org/2025"

  # List of Sponsors
  Sponsors:
    - name: "NXP"
      logo: "/img/logo-nxp.png"
      url: "https://www.facebook.com/vinolanxp"

  # List of Partners
  Partners:
    - name: "Asociația pentru Tehnologie și Internet"
      logo: "/img/logo-apti.png"
      url: "https://www.apti.ro/"

  # List of Organizers
  Organizers:
    - name: "POLITEHNICA Bucharest"
      logo: "/img/logo-unstpb.png"
      url: "https://www.upb.ro"
    - name: "Faculty of Automatic Controls and Computers"
      logo: "/img/logo-acs.png"
      url: "https://acs.pub.ro"
    - name: "ROSEdu (Romanian Open Source Education)"
      logo: "/img/logo-rosedu.png"
      url: "https://www.rosedu.org"
